### PR TITLE
Python 3.4 compatible

### PR DESCRIPTION
**Pull request by brentpayne**
This makes this package 2.7/3.4 compatible.

Most of the required changes were to convert

```python 
print "something"
```

into

```python
print("something")
```

It also handles unicode and byte strings conversions and functions that return iterators instead of lists in python 3.4

It sets up tox for testing both 2.7 and 3.4, and has a default pylint configuration.  

I used pylint to look for other 27/34 issues.

Let me know if you want changes, I'm trying to get usaddress 3.4 compatible and this is a preq for that.

### CODE REVIEW

**Comment by brentpayne** [comment]
It should be noted that I update the version number with this pull request

**Comment by cathydeng** [comment]
thanks, @brentpayne!

**Comment by fgregg** [comment]
Thanks @brentpayne, would love to see that PR for usaddress too.

**Comment by brentpayne** [comment]
doing a presentation tonight, but I should get to double check and push it in tomorrow

**Comment by cathydeng** [comment]
hey @brentpayne - are you building your own parser using parserator? if so, I'm happy to answer questions & clarify anything that's unclear in the [documentation](http://parserator.rtfd.org/). we want to make it as easy as possible to set up a new parser, so we're eager to help someone outside our company use it!

**Comment by brentpayne** [comment]
nope, not right now, just wanted to integrate usaddress into a python3 script

**Comment by brentpayne** [comment]
but I might look into it for doing a local meetup talk in the future.  Is it all linear chain CRFs under the hood?

**Comment by fgregg** [comment]
Yup!

**Pull request merged**
