### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by brentpayne**
adding Unidecode==0.4.17 required dependency

### CODE REVIEW

**Comment by brentpayne** [comment]
unidecode is imported in *parserator/manual_labeling.py* but missing from the requirements.txt.  This pull request adds it in there.

**Comment by cathydeng** [comment]
Hey @brentpayne - thanks for the catch! I added unidecode to setup.py instead (we're keeping requirements for using parserator there, while requirements.txt includes requirements for testing/development)

**Comment by brentpayne** [comment]
got it, generally people will name it test_requirements.txt.  

You can also import requirements.txt into setup.py:
http://stackoverflow.com/questions/14399534/how-can-i-reference-requirements-txt-for-the-install-requires-kwarg-in-setuptool

**Comment by fgregg** [comment]
Interseting, but that doesn't work as well for packaging.

**Comment by brentpayne** [comment]
It will still pull in the requirements.txt dependencies when packaging.  Just not the test_requirements.txt dependencies.  lxml doesn't need to be in the test_requirements.txt since it is a project dependency.

**Pull request closed without merging**
